### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by KarenMendozaGarza** [KarenMendozaGarza/components-on-a-grid#1]
Hello, 

Please find attached my spoken CSS code.

Have a great week!

Karen

[mendoza-karen-030-speak-the-answers.m4a.zip](https://github.com/KarenMendozaGarza/components-on-a-grid/files/7199680/mendoza-karen-030-speak-the-answers.m4a.zip)

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Looks good and sounds good! Nothing to really comment on other than the point I covered in class about `grid-area` competing with `grid-colum/row`

keep it up 👍
